name: Build ShadowSmpCore

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java 21
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode clean package

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: ShadowSmpCore
          path: target/*.jar
